#include "engine.h"

// Stub audio shim - enough to not crash, real audio in Phase 6
void register_audio_shim(JSCContext *ctx) {
    jsc_context_evaluate(ctx,
        "function Audio(src) {"
        "  this.src = src || '';"
        "  this.volume = 1.0;"
        "  this.loop = false;"
        "  this.paused = true;"
        "  this.currentTime = 0;"
        "  this.duration = 0;"
        "  this.readyState = 4;"
        "  this.oncanplaythrough = null;"
        "  this.onended = null;"
        "  this.onerror = null;"
        "  this.onload = null;"
        "  this.play = function(){ this.paused = false; return Promise.resolve(); };"
        "  this.pause = function(){ this.paused = true; };"
        "  this.load = function(){};"
        "  this.addEventListener = function(){};"
        "  this.removeEventListener = function(){};"
        "  this.cloneNode = function(){ return new Audio(this.src); };"
        "  this.canPlayType = function(type){ return 'maybe'; };"
        "}"
        "window.Audio = Audio;"
        "window.AudioContext = window.AudioContext || function() {"
        "  this.state = 'running';"
        "  this.currentTime = 0;"
        "  this.sampleRate = 44100;"
        "  this.destination = {};"
        "  this.createGain = function(){ return { gain: { value: 1, setValueAtTime: function(){} }, connect: function(){}, disconnect: function(){} }; };"
        "  this.createBufferSource = function(){ return { buffer: null, loop: false, connect: function(){}, start: function(){}, stop: function(){}, addEventListener: function(){} }; };"
        "  this.createOscillator = function(){ return { frequency: { value: 440 }, connect: function(){}, start: function(){}, stop: function(){} }; };"
        "  this.decodeAudioData = function(buf, ok, err){ if(ok) setTimeout(function(){ ok({}); }, 0); };"
        "  this.resume = function(){ return Promise.resolve(); };"
        "  this.close = function(){ return Promise.resolve(); };"
        "};"
        "window.webkitAudioContext = window.AudioContext;"
        , -1);
}
